# Generated by Django 4.2.2 on 2024-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.IntegerField(default=1, verbose_name="Work Owner")),
                (
                    "main",
                    models.FileField(blank=True, null=True, upload_to="strategies/"),
                ),
            ],
        ),
    ]
