# Generated by Django 4.2.2 on 2024-02-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import strategy.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("strategy", "0002_remove_strategy_owner_strategy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="main",
            field=models.FileField(
                blank=True, null=True, upload_to=strategy.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
